"""
Image storage. Uploaded photos are checked, oriented, resized, stripped of
camera data (such as GPS location) and saved as WebP, then stored:

- "local": on disk in MEDIA_ROOT, served at /media (development);
- "cloudinary": on Cloudinary's CDN (production), when IMAGE_PROVIDER=cloudinary.

The database keeps only which storage, the key and the URL, so photos stored
either way keep working.
"""

import hashlib
import io
import logging
import time
import uuid
from dataclasses import dataclass
from pathlib import Path

import httpx
from PIL import Image, ImageOps, UnidentifiedImageError

from app.core.config import get_settings

logger = logging.getLogger(__name__)

MAX_UPLOAD_BYTES = 15 * 1024 * 1024
# Longest side kept; next/image serves smaller sizes from this.
MAX_EDGE = 2400
ALLOWED_FORMATS = {"JPEG", "PNG", "WEBP", "AVIF", "MPO"}  # MPO: some phone JPEGs

# Refuse decompression bombs outright rather than warning.
Image.MAX_IMAGE_PIXELS = 60_000_000

MEDIA_URL_PREFIX = "/media/"
CLOUDINARY_API = "https://api.cloudinary.com/v1_1"


class InvalidImage(ValueError):
    """The upload is not an image we accept. The message is safe to show."""


class StorageUnavailable(RuntimeError):
    """The image could not be stored right now (e.g. Cloudinary unreachable)."""


@dataclass(frozen=True)
class StoredImage:
    storage: str
    key: str
    url: str
    width: int
    height: int


def prepare(data: bytes) -> tuple[bytes, int, int]:
    """Checks a photo and returns it as WebP, at most MAX_EDGE wide or tall."""
    if len(data) > MAX_UPLOAD_BYTES:
        raise InvalidImage("The photo is too large (15 MB at most).")
    try:
        with Image.open(io.BytesIO(data)) as source:
            if source.format not in ALLOWED_FORMATS:
                raise InvalidImage("Please upload a JPEG, PNG, WebP or AVIF photo.")
            image = ImageOps.exif_transpose(source)
            image.load()
    except (UnidentifiedImageError, Image.DecompressionBombError, OSError) as exc:
        raise InvalidImage("This file could not be read as a photo.") from exc

    if image.mode not in ("RGB", "RGBA"):
        image = image.convert("RGBA" if "A" in image.getbands() else "RGB")
    image.thumbnail((MAX_EDGE, MAX_EDGE), Image.Resampling.LANCZOS)

    output = io.BytesIO()
    # Saving without exif drops camera metadata such as GPS location.
    image.save(output, "WEBP", quality=82, method=4)
    return output.getvalue(), image.width, image.height


# ——— Local disk ———


def _media_root() -> Path:
    root = get_settings().media_root
    root.mkdir(parents=True, exist_ok=True)
    return root


def _save_local(webp: bytes) -> tuple[str, str]:
    key = f"{uuid.uuid4().hex}.webp"
    (_media_root() / key).write_bytes(webp)
    return key, f"{MEDIA_URL_PREFIX}{key}"


def _delete_local(key: str) -> None:
    # Keys are generated by `_save_local`; refuse anything that could leave the folder.
    if "/" in key or "\\" in key or key.startswith("."):
        return
    (_media_root() / key).unlink(missing_ok=True)


# ——— Cloudinary ———


def cloudinary_signature(params: dict[str, str], secret: str) -> str:
    """Cloudinary's request signature: sorted "key=value" pairs plus the secret, SHA-1."""
    payload = "&".join(f"{key}={params[key]}" for key in sorted(params))
    return hashlib.sha1(f"{payload}{secret}".encode()).hexdigest()


def _cloudinary_call(action: str, params: dict[str, str], files=None) -> dict:
    settings = get_settings()
    signed = {**params, "timestamp": str(int(time.time()))}
    body = {
        **signed,
        "api_key": settings.cloudinary_api_key,
        "signature": cloudinary_signature(signed, settings.cloudinary_api_secret or ""),
    }
    url = f"{CLOUDINARY_API}/{settings.cloudinary_cloud_name}/image/{action}"
    try:
        response = httpx.post(url, data=body, files=files, timeout=60)
        response.raise_for_status()
    except httpx.HTTPError as exc:
        logger.error("Cloudinary %s failed: %s", action, exc)
        raise StorageUnavailable("The photo could not be stored. Please try again.") from exc
    return response.json()


def _save_cloudinary(webp: bytes) -> tuple[str, str]:
    result = _cloudinary_call(
        "upload",
        {"folder": get_settings().cloudinary_folder, "public_id": uuid.uuid4().hex},
        files={"file": ("photo.webp", webp, "image/webp")},
    )
    return result["public_id"], result["secure_url"]


def _delete_cloudinary(public_id: str) -> None:
    try:
        _cloudinary_call("destroy", {"public_id": public_id})
    except StorageUnavailable:
        # The photo is already gone from the site; a leftover file isn't worth an error.
        logger.warning("Could not delete %s from Cloudinary", public_id)


# ——— Public interface ———


def save(data: bytes) -> StoredImage:
    webp, width, height = prepare(data)
    if get_settings().image_provider == "cloudinary":
        key, url = _save_cloudinary(webp)
        return StoredImage("cloudinary", key, url, width, height)
    key, url = _save_local(webp)
    return StoredImage("local", key, url, width, height)


def delete(storage: str, key: str) -> None:
    if storage == "cloudinary":
        _delete_cloudinary(key)
    elif storage == "local":
        _delete_local(key)
