"""add catalog portfolio media and business settings

Revision ID: 2cb72d022db0
Revises: dede676a90fb
Create Date: 2026-10-01 13:08:03.396981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb72d022db0'
down_revision: Union[str, Sequence[str], None] = 'dede676a90fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('street', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('maps_url', sa.String(length=1000), nullable=True),
    sa.Column('instagram', sa.String(length=30), nullable=True),
    sa.Column('facebook_url', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_business_settings_single_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_settings'))
    )
    op.create_table('media_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("storage IN ('local', 'external')", name=op.f('ck_media_assets_storage')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('key', name=op.f('uq_media_assets_key'))
    )
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name_sq', sa.String(length=80), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=True),
    sa.Column('description_sq', sa.String(length=300), nullable=True),
    sa.Column('description_en', sa.String(length=300), nullable=True),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['media_assets.id'], name=op.f('fk_categories_image_id_media_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('portfolio_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title_sq', sa.String(length=120), nullable=False),
    sa.Column('title_en', sa.String(length=120), nullable=True),
    sa.Column('description_sq', sa.String(length=1000), nullable=True),
    sa.Column('description_en', sa.String(length=1000), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_portfolio_items_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_items')),
    sa.UniqueConstraint('slug', name=op.f('uq_portfolio_items_slug'))
    )
    op.create_index(op.f('ix_portfolio_items_category_id'), 'portfolio_items', ['category_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name_sq', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('description_sq', sa.String(length=500), nullable=True),
    sa.Column('description_en', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price_type', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(price_type = 'on_request') = (price IS NULL)", name=op.f('ck_services_price_matches_type')),
    sa.CheckConstraint("price_type IN ('fixed', 'from', 'on_request')", name=op.f('ck_services_price_type')),
    sa.CheckConstraint('duration_minutes IS NULL OR duration_minutes > 0', name=op.f('ck_services_duration_positive')),
    sa.CheckConstraint('price IS NULL OR price >= 0', name=op.f('ck_services_price_not_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_services_category_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('slug', name=op.f('uq_services_slug'))
    )
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.create_table('portfolio_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['portfolio_items.id'], name=op.f('fk_portfolio_images_item_id_portfolio_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], name=op.f('fk_portfolio_images_media_id_media_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_images')),
    sa.UniqueConstraint('media_id', name=op.f('uq_portfolio_images_media_id'))
    )
    op.create_index(op.f('ix_portfolio_images_item_id'), 'portfolio_images', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_images_item_id'), table_name='portfolio_images')
    op.drop_table('portfolio_images')
    op.drop_index(op.f('ix_services_category_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_portfolio_items_category_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_table('categories')
    op.drop_table('media_assets')
    op.drop_table('business_settings')
    # ### end Alembic commands ###
