"""add schedule: business hours, blocked periods, booking settings

Revision ID: dede676a90fb
Revises: 1422910b3b81
Create Date: 2026-10-01 12:51:33.946051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dede676a90fb'
down_revision: Union[str, Sequence[str], None] = '1422910b3b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('starts_on <= ends_on', name=op.f('ck_blocked_periods_ordered_dates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocked_periods'))
    )
    op.create_index(op.f('ix_blocked_periods_starts_on'), 'blocked_periods', ['starts_on'], unique=False)
    op.create_table('booking_settings',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('slot_interval_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('min_notice_minutes', sa.Integer(), nullable=False),
    sa.Column('booking_window_days', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('booking_window_days > 0', name=op.f('ck_booking_settings_positive_window')),
    sa.CheckConstraint('id = 1', name=op.f('ck_booking_settings_single_row')),
    sa.CheckConstraint('min_notice_minutes >= 0', name=op.f('ck_booking_settings_non_negative_notice')),
    sa.CheckConstraint('slot_interval_minutes > 0', name=op.f('ck_booking_settings_positive_interval')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_settings'))
    )
    op.create_table('business_hours',
    sa.Column('weekday', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.CheckConstraint('NOT is_open OR (opens_at IS NOT NULL AND closes_at IS NOT NULL AND opens_at < closes_at)', name=op.f('ck_business_hours_open_day_has_hours')),
    sa.CheckConstraint('weekday BETWEEN 1 AND 7', name=op.f('ck_business_hours_weekday_range')),
    sa.PrimaryKeyConstraint('weekday', name=op.f('pk_business_hours'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_hours')
    op.drop_table('booking_settings')
    op.drop_index(op.f('ix_blocked_periods_starts_on'), table_name='blocked_periods')
    op.drop_table('blocked_periods')
    # ### end Alembic commands ###
