"""admin password resets

Revision ID: ea28b7e93667
Revises: 3b90a7e505c4
Create Date: 2026-10-01 19:35:43.939035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea28b7e93667'
down_revision: Union[str, Sequence[str], None] = '3b90a7e505c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_password_resets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_admin_password_resets_admin_id_admins'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_password_resets')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_admin_password_resets_token_hash'))
    )
    op.create_index(op.f('ix_admin_password_resets_admin_id'), 'admin_password_resets', ['admin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_password_resets_admin_id'), table_name='admin_password_resets')
    op.drop_table('admin_password_resets')
    # ### end Alembic commands ###
