"""add daily break to business hours

Revision ID: 7569872dba26
Revises: 9994c62dfe40
Create Date: 2026-10-01 13:38:31.879464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7569872dba26'
down_revision: Union[str, Sequence[str], None] = '9994c62dfe40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_hours', sa.Column('break_starts_at', sa.Time(), nullable=True))
    op.add_column('business_hours', sa.Column('break_ends_at', sa.Time(), nullable=True))
    op.create_check_constraint(
        op.f('ck_business_hours_break_complete'),
        'business_hours',
        '(break_starts_at IS NULL) = (break_ends_at IS NULL)',
    )
    op.create_check_constraint(
        op.f('ck_business_hours_break_within_hours'),
        'business_hours',
        'break_starts_at IS NULL OR (break_starts_at < break_ends_at'
        ' AND break_starts_at >= opens_at AND break_ends_at <= closes_at)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_business_hours_break_within_hours'), 'business_hours', type_='check')
    op.drop_constraint(op.f('ck_business_hours_break_complete'), 'business_hours', type_='check')
    op.drop_column('business_hours', 'break_ends_at')
    op.drop_column('business_hours', 'break_starts_at')
    # ### end Alembic commands ###
