"""booking items locations buffers policy

Revision ID: 3c59511664d4
Revises: 87ca8d4fe1d6
Create Date: 2026-10-01 14:06:56.095045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c59511664d4'
down_revision: Union[str, Sequence[str], None] = '87ca8d4fe1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('name_sq', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity BETWEEN 1 AND 20', name=op.f('ck_booking_items_quantity_range')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_items_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_booking_items_service_id_services'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_items'))
    )
    op.create_index(op.f('ix_booking_items_booking_id'), 'booking_items', ['booking_id'], unique=False)
    op.add_column('booking_settings', sa.Column('buffer_minutes', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('booking_settings', sa.Column('home_visits', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('booking_settings', sa.Column('travel_minutes', sa.SmallInteger(), server_default='30', nullable=False))
    op.add_column('booking_settings', sa.Column('home_visit_note_sq', sa.String(length=300), nullable=True))
    op.add_column('booking_settings', sa.Column('home_visit_note_en', sa.String(length=300), nullable=True))
    op.add_column('booking_settings', sa.Column('cancellation_notice_hours', sa.SmallInteger(), server_default='24', nullable=False))
    op.add_column('booking_settings', sa.Column('policy_sq', sa.String(length=1000), nullable=True))
    op.add_column('booking_settings', sa.Column('policy_en', sa.String(length=1000), nullable=True))
    op.add_column('bookings', sa.Column('block_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('block_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('location', sa.String(length=10), server_default='studio', nullable=False))
    op.add_column('bookings', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('bookings', sa.Column('manage_token', sa.String(length=64), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_by', sa.String(length=10), nullable=True))
    op.add_column('bookings', sa.Column('client_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('bookings', 'service_name_sq',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('bookings', 'service_name_en',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_bookings_manage_token'), 'bookings', ['manage_token'])
    # ### end Alembic commands ###

    # Existing bookings: no travel or preparation time, a fresh private link,
    # and one item each, taken from their summary.
    op.execute("UPDATE bookings SET block_start = start_time, block_end = end_time")
    op.execute("UPDATE bookings SET manage_token = replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '')")
    op.alter_column('bookings', 'block_start', nullable=False)
    op.alter_column('bookings', 'block_end', nullable=False)
    op.alter_column('bookings', 'manage_token', nullable=False)
    op.execute(
        "INSERT INTO booking_items (id, booking_id, service_id, name_sq, name_en, duration_minutes,"
        " price, price_type, quantity, sort_order)"
        " SELECT gen_random_uuid(), id, service_id, left(service_name_sq, 100), left(service_name_en, 100),"
        " (extract(epoch FROM end_time - start_time) / 60)::int, price, price_type, 1, 0 FROM bookings"
    )

    op.create_check_constraint(op.f('ck_bookings_location'), 'bookings', "location IN ('studio', 'client')")
    op.create_check_constraint(op.f('ck_bookings_cancelled_by'), 'bookings', "cancelled_by IN ('client', 'admin')")
    op.create_check_constraint(
        op.f('ck_bookings_block_covers_appointment'),
        'bookings',
        'block_start <= start_time AND block_end >= end_time',
    )
    op.drop_constraint(op.f('ck_bookings_status'), 'bookings', type_='check')
    op.create_check_constraint(
        op.f('ck_bookings_status'),
        'bookings',
        "status IN ('pending', 'confirmed', 'declined', 'cancelled', 'completed', 'no_show', 'expired')",
    )
    _overlap_rule('block_start', 'block_end')
    op.create_check_constraint(op.f('ck_booking_settings_non_negative_buffer'), 'booking_settings', 'buffer_minutes >= 0')
    op.create_check_constraint(op.f('ck_booking_settings_non_negative_travel'), 'booking_settings', 'travel_minutes >= 0')
    op.create_check_constraint(
        op.f('ck_booking_settings_non_negative_cancellation'), 'booking_settings', 'cancellation_notice_hours >= 0'
    )


def _overlap_rule(start: str, end: str) -> None:
    op.execute("ALTER TABLE bookings DROP CONSTRAINT ex_bookings_no_overlap")
    op.execute(
        "ALTER TABLE bookings ADD CONSTRAINT ex_bookings_no_overlap "
        f"EXCLUDE USING gist (tstzrange({start}, {end}, '[)') WITH &&) WHERE (status = 'confirmed')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    _overlap_rule('start_time', 'end_time')
    op.execute("UPDATE bookings SET status = 'cancelled' WHERE status = 'expired'")
    op.drop_constraint(op.f('ck_bookings_status'), 'bookings', type_='check')
    op.create_check_constraint(
        op.f('ck_bookings_status'),
        'bookings',
        "status IN ('pending', 'confirmed', 'declined', 'cancelled', 'completed', 'no_show')",
    )
    for name in ('location', 'cancelled_by', 'block_covers_appointment'):
        op.drop_constraint(op.f(f'ck_bookings_{name}'), 'bookings', type_='check')
    for name in ('non_negative_buffer', 'non_negative_travel', 'non_negative_cancellation'):
        op.drop_constraint(op.f(f'ck_booking_settings_{name}'), 'booking_settings', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_bookings_manage_token'), 'bookings', type_='unique')
    op.alter_column('bookings', 'service_name_en',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('bookings', 'service_name_sq',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('bookings', 'reminder_sent_at')
    op.drop_column('bookings', 'client_changed_at')
    op.drop_column('bookings', 'cancelled_by')
    op.drop_column('bookings', 'manage_token')
    op.drop_column('bookings', 'address')
    op.drop_column('bookings', 'location')
    op.drop_column('bookings', 'block_end')
    op.drop_column('bookings', 'block_start')
    op.drop_column('booking_settings', 'policy_en')
    op.drop_column('booking_settings', 'policy_sq')
    op.drop_column('booking_settings', 'cancellation_notice_hours')
    op.drop_column('booking_settings', 'home_visit_note_en')
    op.drop_column('booking_settings', 'home_visit_note_sq')
    op.drop_column('booking_settings', 'travel_minutes')
    op.drop_column('booking_settings', 'home_visits')
    op.drop_column('booking_settings', 'buffer_minutes')
    op.drop_index(op.f('ix_booking_items_booking_id'), table_name='booking_items')
    op.drop_table('booking_items')
    # ### end Alembic commands ###
