"""add bookings

Revision ID: 9994c62dfe40
Revises: 2cb72d022db0
Create Date: 2026-10-01 13:24:25.148853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9994c62dfe40'
down_revision: Union[str, Sequence[str], None] = '2cb72d022db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('service_name_sq', sa.String(length=100), nullable=False),
    sa.Column('service_name_en', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price_type', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('customer_phone', sa.String(length=40), nullable=False),
    sa.Column('customer_email', sa.String(length=254), nullable=True),
    sa.Column('customer_note', sa.String(length=1000), nullable=True),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('admin_message', sa.String(length=1000), nullable=True),
    sa.Column('admin_note', sa.String(length=2000), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.text("tstzrange(start_time, end_time, '[)')"), '&&'), where=sa.text("status IN ('pending', 'confirmed')"), using='gist', name='ex_bookings_no_overlap'),
    sa.CheckConstraint("locale IN ('sq', 'en')", name=op.f('ck_bookings_locale')),
    sa.CheckConstraint("source IN ('website', 'admin')", name=op.f('ck_bookings_source')),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'declined', 'cancelled', 'completed', 'no_show')", name=op.f('ck_bookings_status')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_bookings_ends_after_start')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_bookings_service_id_services'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('reference', name=op.f('uq_bookings_reference'))
    )
    op.create_index(op.f('ix_bookings_service_id'), 'bookings', ['service_id'], unique=False)
    op.create_index(op.f('ix_bookings_start_time'), 'bookings', ['start_time'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_service_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
