"""rate limit events

Revision ID: 7abf65d7bffa
Revises: 3c59511664d4
Create Date: 2026-10-01 19:30:43.803410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7abf65d7bffa'
down_revision: Union[str, Sequence[str], None] = '3c59511664d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_limit_events'))
    )
    op.create_index('ix_rate_limit_events_lookup', 'rate_limit_events', ['scope', 'key', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rate_limit_events_lookup', table_name='rate_limit_events')
    op.drop_table('rate_limit_events')
    # ### end Alembic commands ###
